"""Merges kaggriculture/*.py into a single main.py for submission (SDD §9).

Strips internal cross-module imports (`from .foo import ...` / `from
kaggriculture...`), de-duplicates external imports, concatenates module
bodies in dependency order, writes main.py, then sanity-checks with
compile() before treating it as submission-ready.
"""

import ast
import pathlib

PKG_DIR = pathlib.Path(__file__).parent / "kaggriculture"
OUTPUT = pathlib.Path(__file__).parent / "main.py"

# Dependency order: config has no internal deps; market_model depends only
# on config; state depends on config; strategy depends on config+state;
# farm_ops depends on config+state+strategy+market_model; agent wires all of
# them together and must come last.
MODULE_ORDER = ["config.py", "market_model.py", "state.py", "strategy.py", "farm_ops.py", "agent.py"]


def is_internal_import(node) -> bool:
    if isinstance(node, ast.ImportFrom):
        return node.level > 0 or (node.module and node.module.startswith("kaggriculture"))
    return False


def split_imports_and_body(source: str):
    """Returns (external_import_source_list, body_with_all_top-level_imports_stripped).

    Uses AST line ranges (not per-line regex) so multi-line parenthesized
    imports are stripped/collected correctly regardless of how they wrap.
    """
    tree = ast.parse(source)
    lines = source.splitlines()
    remove_lines = set()
    external_imports = []
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            for lineno in range(node.lineno, (node.end_lineno or node.lineno) + 1):
                remove_lines.add(lineno)
            if not is_internal_import(node):
                segment = ast.get_source_segment(source, node)
                if segment:
                    external_imports.append(segment)
    body = "\n".join(line for i, line in enumerate(lines, start=1) if i not in remove_lines)
    return external_imports, body


def build():
    all_imports = []
    bodies = []
    for name in MODULE_ORDER:
        path = PKG_DIR / name
        source = path.read_text(encoding="utf-8")
        external_imports, body = split_imports_and_body(source)
        all_imports.extend(external_imports)
        bodies.append(f"# ==== {name} ====\n{body.strip()}\n")

    seen = set()
    dedup_imports = []
    for imp in all_imports:
        if imp not in seen:
            seen.add(imp)
            dedup_imports.append(imp)

    header = "# GENERATED by build_submission.py — do not edit directly.\n"
    content = header + "\n".join(dedup_imports) + "\n\n" + "\n".join(bodies)

    compile(content, str(OUTPUT), "exec")

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT} ({len(content)} bytes), compile() OK.")


if __name__ == "__main__":
    build()
